title: Citrus-Melon
logo: /images/logo.svg
description: <br>I am a self-taught student learning to code by doing fun, random projects! I'm interested in web development, game design, and more.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal