title: Citrus-Melon -- Maxwell's Website
logo: /assets/img/logo.png
description: Hi, I'm Maxwell, a beginner/hobbyist in web development and coding in general.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal